service: aws-lambda-prueba
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      
      Resource:
        - arn:aws:dynamodb:us-east-1:503235614140:table/TaskTable2
        - arn:aws:dynamodb:us-east-1:503235614140:table/UserTable
        - arn:aws:dynamodb:us-east-1:503235614140:table:ImageTable
        - arn:aws:dynamodb:us-east-1:503235614140:table/PointTable
        - arn:aws:dynamodb:us-east-1:503235614140:table/ProductTable
       

        
functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get
  getImages:
    handler: src/getImages.getImages
    events:
      - httpApi:
          path: /images
          method: get
  createTask:
    handler: src/addTask.addTask
    events:
      - httpApi:
          path: /tasks
          method: post
  getTasks:
    handler: src/getTasks.getTasks
    events:
      - httpApi:
          path: /tasks
          method: get
  getTask:
    handler: src/getTask.getTask
    events:
      - httpApi:
          path: /tasks/{id} 
          method: get        
  updateTask:
     handler: src/updateTask.updateTask
     events:
       - httpApi:
           path: /tasks/{id}
           method: put 
  deleteTask:
     handler: src/deleteTask.deleteTask
     events:
       - httpApi:
           path: /tasks/{id}
           method: delete

  createUser:
    handler: src/addUser.addUser
    events:
      - httpApi:
          path: /users
          method: post  
  getUsers:
    handler: src/getUsers.getUsers
    events:
      - httpApi:
          path: /users
          method: get
  getUser:
    handler: src/getUser.getUser
    events:
      - httpApi:
          path: /users/{id} 
          method: get        
  updateUser:
     handler: src/updateUser.updateUser
     events:
       - httpApi:
           path: /users/{id}
           method: put 
  deleteUser:
     handler: src/deleteUser.deleteUser
     events:
       - httpApi:
           path: /users/{id}
           method: delete 


  createPoint:
    handler: src/addPoints.addPoints
    events:
      - httpApi:
          path: /points
          method: post
  
  getPoints:
    handler: src/getPoints.getPoints
    events:
      - httpApi:
          path: /points
          method: get

  getPoint:
    handler: src/getPoint.getPoint
    events:
      - httpApi:
          path: /points/{id}
          method: get

  getPointsByUser:
    handler: src/getPoint.getPointsByUser
    events:
      - httpApi:
          path: /points/user/{username}
          method: get

  updatePoint:
    handler: src/updatePoint.updatePoint
    events:
      - httpApi:
          path: /points/{id}
          method: put
  deletePoint:
    handler: src/deletePoint.deletePoint
    events:
      - httpApi:
        path: /points/{id}
        method: delete
  
  createProduct:
    handler: src/addProducts.addProducts
    events:
      - httpApi:
          path: /products
          method: post
  
  getProducts:
    handler: src/getProducts.getProducts
    events:
      - httpApi:
          path: /products
          method: get

  getProduct:
    handler: src/getProduct.getProduct
    events:
      - httpApi:
          path: /products/{id}
          method: get

  updateProduct:
    handler: src/updateProduct.updateProduct
    events:
      - httpApi:
          path: /products/{id}
          method: put

  deleteProduct:
    handler: src/deleteProduct.deleteProduct
    events:
      - httpApi:
        path: /products/{id}
        method: delete  


resources:
  Resources:
    TaskTable2:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable2
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH   
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
       
    PointTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PointTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
            - AttributeName: id
              KeyType: HASH
    ProductTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
            - AttributeName: id
              KeyType: HASH  
    ImageTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ImageTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH   